stages:
  - style
  - test

# Check that the style of source files respects
# the coding convention.
check_style:
  stage: style
  image: ubuntu:20.04
  before_script:
    - apt -y update
    - apt -y install clang-format git
  script:
    - misc/fix-style --check

# Check that headers are up-to-date.
check_headers:
  stage: style
  image: debian:stable
  before_script:
    - apt -y update
    - apt -y install python git
  script:
    - misc/update-headers --check

# Check that some examples compile without error or warning
compile:
  stage: test
  image: debian:stable
  before_script:
    - apt -y update
    - apt -y install build-essential mtools perl libxml-libxml-perl libxml-simple-perl libfile-copy-recursive-perl bc
  script:
    - make configure
    - (cd examples/mutexes && make CC="gcc -Wall -Wextra -Werror")
    - (cd examples/semaphores && make CC="gcc -Wall -Wextra -Werror")
    - (cd examples/events && make CC="gcc -Wall -Wextra -Werror")

# Run tests for utilities
test_utils:
  stage: test
  image: debian:stable
  before_script:
    - apt -y update
    - apt -y install python3 python3-yaml
  script:
    - python3 misc/gen_dependencies --test
    - python3 misc/gen_deployment --test

unit_tests:
  stage: test
  image: debian:stable
  before_script:
    - apt -y update
    - apt -y install build-essential mtools perl libxml-libxml-perl libxml-simple-perl libfile-copy-recursive-perl bc python3 python3-venv qemu-system-x86 clang
  script:
    - make configure
    - python3 -mvenv venv
    - source venv/bin/activate
    - pip install -r misc/requirements.txt
    - make -C testsuite/unitary_tests check
  artifacts:
    reports:
      junit: testsuite/unitary_tests/report.xml
