stages:
  - style
  - compile

check_style:
  stage: style
  image: ubuntu:20.04
  before_script:
    - apt -y update
    - apt -y install clang-format git
  script:
    - misc/fix-style --check

check_headers:
  stage: style
  image: debian:stable
  before_script:
    - apt -y update
    - apt -y install python git
  script:
    - misc/update-headers --check

compile:
  stage: compile
  image: debian:stable
  before_script:
    - apt -y update
    - apt -y install build-essential mtools perl libxml-libxml-perl libxml-simple-perl libfile-copy-recursive-perl bc
  script:
    - make configure
    - (cd examples/mutexes && make CC="gcc -march=pentium -Wall -Wextra -Werror")
    - (cd examples/semaphores && make CC="gcc -march=pentium -Wall -Wextra -Werror")
